name: aerobat
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - seaborn
  - pandas
  - matplotlib
  - pygame
  - six
  - pyyaml
  - pip
  - pip:
      - "pip<24"
      - "setuptools<66"
      - "wheel<0.39"
      - "gymnasium>=1.2,<1.3"
      - pyglet
      - moderngl
      - opencv-python
      - "PyQt6==6.4.2"
      - "PyQt6-Qt6==6.4.2"
      - "PyQt6-sip==13.4.1"
      - imageio
      - Pillow
